export interface DadataSuggestion {
  value: string | null,
  unrestricted_value: string | null,
  data: {
    postal_code: number,
    country: string,
    country_iso_code: string,
    federal_district: string | number | null,
    region_fias_id: string | number | null,
    region_kladr_id: number,
    region_iso_code: string | number | null,
    region_with_type: string | number | null,
    region_type: string | number | null,
    region_type_full: string | number | null,
    region: string | number | null,
    area_fias_id: string | number | null,
    area_kladr_id: string | number | null,
    area_with_type: string | number | null,
    area_type: string | number | null,
    area_type_full: string | number | null,
    area: string | number | null,
    city_fias_id: string | number | null,
    city_kladr_id: string | number | null,
    city_with_type: string | number | null,
    city_type: string | number | null,
    city_type_full: string | number | null,
    city: string | number | null,
    city_area: string | number | null,
    city_district_fias_id: string | number | null,
    city_district_kladr_id: string | number | null,
    city_district_with_type: string | number | null,
    city_district_type: string | number | null,
    city_district_type_full: string | number | null,
    city_district: string | number | null,
    settlement_fias_id: string | number | null,
    settlement_kladr_id: string | number | null,
    settlement_with_type: string | number | null,
    settlement_type: string | number | null,
    settlement_type_full: string | number | null,
    settlement: string | number | null,
    street_fias_id: string | number | null,
    street_kladr_id: string | number | null,
    street_with_type: string | number | null,
    street_type: string | number | null,
    street_type_full: string | number | null,
    street: string | number | null,
    stead_fias_id: string | number | null,
    stead_cadnum: string | number | null,
    stead_type: string | number | null,
    stead_type_full: string | number | null,
    stead: string | number | null,
    house_fias_id: string | number | null,
    house_kladr_id: string | number | null,
    house_cadnum: string | number | null,
    house_flat_count: string | number | null,
    house_type: string | number | null,
    house_type_full: null,
    house: string | number | null,
    block_type: string | number | null,
    block_type_full: string | number | null,
    block: string | number | null,
    entrance: null,
    floor: string | number | null,
    flat_fias_id: string | number | null,
    flat_cadnum: string | number | null,
    flat_type: string | number | null,
    flat_type_full: string | number | null,
    flat: string | number | null,
    flat_area: string | number | null,
    square_meter_price: string | number | null,
    flat_price: string | number | null,
    room_fias_id: string | number | null,
    room_cadnum: string | number | null,
    room_type: string | number | null,
    room_type_full: string | number | null,
    room: string | number | null,
    postal_box: string | number | null,
    fias_id: string | number | null,
    fias_code: string | number | null,
    fias_level: string | number | null,
    fias_actuality_state: string | number | null,
    kladr_id: string | number | null,
    geoname_id: string | number | null,
    capital_marker: string | number | null,
    okato: string | number | null,
    oktmo: string | number | null,
    tax_office: string | number | null,
    tax_office_legal: string | number | null,
    timezone: string | number | null,
    geo_lat: string | number | null,
    geo_lon: string | number | null,
    beltway_hit: string | number | null,
    beltway_distance: string | number | null,
    metro: string | number | null,
    divisions: string | number | null,
    qc_geo: string | number | null,
    qc_complete: string | number | null,
    qc_house: string | number | null,
    history_values: string[],
    unparsed_parts: string | number | null,
    source: string | number | null,
    qc: string | number | null
  }
}
